version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes: 
      - .:/usr/src
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_URL: "postgres://postgres@db/production"
      DEVELOPMENT_DATABASE_URL: "postgres://postgres@db/development"
      TEST_DATABASE_URL: "postgres://postgres@db/test"
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
