default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  url_development: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>
test:
  <<: *default
  url_test: <%= ENV['TEST_DATABASE_URL'] %>
production:
  <<: *default
